# Perl Best Practices (plus errata) .perltidyrc / perltidy.ini file
-l=98    # Max line width is 98 cols
-i=3    # Indent level is 3 cols
-ci=3    # Continuation indent is 3 cols
#-st     # Output to STDOUT
-se      # Errors to STDERR
-vt=2    # Maximal vertical tightness
-cti=1   # No extra indentation for closing brackets
-pt=1    # Medium parenthesis tightness
-bt=1    # Medium brace tightness
-sbt=1   # Medium square bracket tightness
-bbt=1   # Medium block brace tightness
-nsfs    # No space before semicolons
-nolq    # Don't outdent long quoted strings
-wbb="% + - * / x != == >= <= =~ < > | & **= += *= &= <<= &&= -= /= |= >>= ||= .= %= ^= x="
         # Break before all operators

# Extras/overrides/deviations from Perl Best Practices
--maximum-line-length=78              # Be less generous
--warning-output                      # Show warnings
--maximum-consecutive-blank-lines=2   # Default is 1
--nohanging-side-comments             # Troublesome for commented out code

-isbc   # Block comments may only be indented if they have some space characters before the #
-ci=2   # Continuation indent is 2 cols

# We use version control, so just rewrite the file
-b

# For the up-tight folk :)
-pt=0    # parenthesis tightness
-bt=0    # brace tightness
-sbt=0   # square bracket tightness